### ISSUE TITLE
Outstanding work for 8.0 release

### ISSUE THREAD

**Issue by chimericdream** [chimericdream/WorldOfPannotia-MC-Modpack#94]
This is a non-exhaustive list of work still to be done for a full 8.0 (1.16) release of the pack.

* [x] Change stair crafting recipes to return 8 instead of 4 [1]
* [x] Change trapdoor crafting recipes to return 12 instead of 2 [1]
* [x] Allow stairs to be crafted back into their respective blocks (#103)
* [x] Allow creation of 2 slabs from 1 block (#104)
* [x] Identify major overlapping content and either disable it or remove unneeded mods (ongoing)
* [x] Wiki work (see the [Quark](https://quark.vazkii.net/#features) and [Charm](https://svenhjol.github.io/Charm/) websites for an idea of how features and pages may be categorized/structured) (#105)
* [x] Official release of Caverns & Chasms [2] (#106)
* [x] Official release of Nether Extension [2] (#107)

Again, this list is certainly not intended to be complete. Any issues created here that are relevant to the 8.x release will be added to the [8.0.0 milestone](https://github.com/chimericdream/WorldOfPannotia-MC-Modpack/milestone/18), so you can view the status there.

If you have a suggestion or find a bug, [feel free to create an issue](https://github.com/chimericdream/WorldOfPannotia-MC-Modpack/issues/new)!

[1] Actual amounts subject to change or some variation depending on the recipe
[2] These mods are currently in private beta and not able to be installed via the launcher

**Comment by chimericdream** [comment]
TODO: split this ticket into separate ones, since we're already on 8.1

**Comment by chimericdream** [comment]
Created standalone tickets for remaining items.
